"CSC309H1-F-20179": {
        "courseId": "10012",
        "org": "CSC",
        "orgName": "Computer Science (CSC) (ECE)",
        "courseTitle": "Programming on the Web",
        "code": "CSC309H1",
        "courseDescription": "An introduction to software development on the web. Concepts underlying the development of programs that operate on the web; survey of technological alternatives; greater depth on some technologies. Operational concepts of the internet and the web, static client content, dynamic client content, dynamically served content, n-tiered architectures, web development processes, and security on the web. Assignments involve increasingly more complex web-based programs. Guest lecturers from leading e-commerce firms will describe the architecture and operation of their web sites.",
        "prerequisite": "CSC209H1",
        "corequisite": "",
        "exclusion": "",
        "recommendedPreparation": "CSC343H1",
        "section": "F",
        "session": "20179",
        "webTimetableInstructions": "",
        "breadthCategories": "The Physical and Mathematical Universes (5)",
        "distributionCategories": "Science",
        "meetings": {
            "LEC-0101": {
                "schedule": {
                    "MO-91006": {
                        "meetingDay": "MO",
                        "meetingStartTime": "15:00",
                        "meetingEndTime": "16:00",
                        "meetingScheduleId": "91006",
                        "assignedRoom1": "GB 244",
                        "assignedRoom2": null
                    },
                    "WE-91007": {
                        "meetingDay": "WE",
                        "meetingStartTime": "15:00",
                        "meetingEndTime": "16:00",
                        "meetingScheduleId": "91007",
                        "assignedRoom1": "GB 244",
                        "assignedRoom2": null
                    },
                    "FR-91008": {
                        "meetingDay": "FR",
                        "meetingStartTime": "15:00",
                        "meetingEndTime": "16:00",
                        "meetingScheduleId": "91008",
                        "assignedRoom1": "GB 244",
                        "assignedRoom2": null
                    }
                },
                "instructors": {
                    "2107220": {
                        "instructorId": "2107220",
                        "firstName": "J",
                        "lastName": "Gonzalez"
                    }
                },
                "meetingId": "16409",
                "teachingMethod": "LEC",
                "sectionNumber": "0101",
                "subtitle": "",
                "cancel": "",
                "waitlist": "Y",
                "online": "",
                "enrollmentCapacity": "85",
                "actualEnrolment": "83",
                "actualWaitlist": "0",
                "enrollmentIndicator": "P",
                "meetingStatusNotes": "",
                "enrollmentControls": [
                    {
                        "postId": "126",
                        "postCode": "ASMAJ1689",
                        "postName": "MA COMPUTER SCIENCE",
                        "subjectId": null,
                        "subjectCode": null,
                        "subjectName": null,
                        "designationId": null,
                        "designationCode": null,
                        "designationName": null,
                        "yearOfStudy": "*",
                        "typeOfProgramId": null,
                        "typeOfProgramCode": null,
                        "typeOfProgramName": null,
                        "primaryOrgId": null,
                        "primaryOrgCode": null,
                        "primaryOrgName": null,
                        "secondaryOrgId": null,
                        "secondaryOrgCode": null,
                        "secondaryOrgName": null,
                        "assocOrgId": null,
                        "assocOrgCode": null,
                        "assocOrgName": null,
                        "adminOrgId": null,
                        "adminOrgCode": null,
                        "adminOrgName": null
                    },
                    {
                        "postId": "127",
                        "postCode": "ASMAJ1689X",
                        "postName": "MA COMPUTER SCIENCE",
                        "subjectId": null,
                        "subjectCode": null,
                        "subjectName": null,
                        "designationId": null,
                        "designationCode": null,
                        "designationName": null,
                        "yearOfStudy": "*",
                        "typeOfProgramId": null,
                        "typeOfProgramCode": null,
                        "typeOfProgramName": null,
                        "primaryOrgId": null,
                        "primaryOrgCode": null,
                        "primaryOrgName": null,
                        "secondaryOrgId": null,
                        "secondaryOrgCode": null,
                        "secondaryOrgName": null,
                        "assocOrgId": null,
                        "assocOrgCode": null,
                        "assocOrgName": null,
                        "adminOrgId": null,
                        "adminOrgCode": null,
                        "adminOrgName": null
                    },
                    {
                        "postId": "212",
                        "postCode": "ASMIN1688",
                        "postName": "MI COMPUTER SCIENCE.",
                        "subjectId": null,
                        "subjectCode": null,
                        "subjectName": null,
                        "designationId": null,
                        "designationCode": null,
                        "designationName": null,
                        "yearOfStudy": "*",
                        "typeOfProgramId": null,
                        "typeOfProgramCode": null,
                        "typeOfProgramName": null,
                        "primaryOrgId": null,
                        "primaryOrgCode": null,
                        "primaryOrgName": null,
                        "secondaryOrgId": null,
                        "secondaryOrgCode": null,
                        "secondaryOrgName": null,
                        "assocOrgId": null,
                        "assocOrgCode": null,
                        "assocOrgName": null,
                        "adminOrgId": null,
                        "adminOrgCode": null,
                        "adminOrgName": null
                    },
                    {
                        "postId": "213",
                        "postCode": "ASMIN1689",
                        "postName": "MI COMPUTER SCIENCE",
                        "subjectId": null,
                        "subjectCode": null,
                        "subjectName": null,
                        "designationId": null,
                        "designationCode": null,
                        "designationName": null,
                        "yearOfStudy": "*",
                        "typeOfProgramId": null,
                        "typeOfProgramCode": null,
                        "typeOfProgramName": null,
                        "primaryOrgId": null,
                        "primaryOrgCode": null,
                        "primaryOrgName": null,
                        "secondaryOrgId": null,
                        "secondaryOrgCode": null,
                        "secondaryOrgName": null,
                        "assocOrgId": null,
                        "assocOrgCode": null,
                        "assocOrgName": null,
                        "adminOrgId": null,
                        "adminOrgCode": null,
                        "adminOrgName": null
                    },
                    {
                        "postId": "335",
                        "postCode": "ASSPE1689",
                        "postName": "SP COMPUTER SCIENCE",
                        "subjectId": null,
                        "subjectCode": null,
                        "subjectName": null,
                        "designationId": null,
                        "designationCode": null,
                        "designationName": null,
                        "yearOfStudy": "*",
                        "typeOfProgramId": null,
                        "typeOfProgramCode": null,
                        "typeOfProgramName": null,
                        "primaryOrgId": null,
                        "primaryOrgCode": null,
                        "primaryOrgName": null,
                        "secondaryOrgId": null,
                        "secondaryOrgCode": null,
                        "secondaryOrgName": null,
                        "assocOrgId": null,
                        "assocOrgCode": null,
                        "assocOrgName": null,
                        "adminOrgId": null,
                        "adminOrgCode": null,
                        "adminOrgName": null
                    },
                    {
                        "postId": "336",
                        "postCode": "ASSPE1689X",
                        "postName": "SP COMPUTER SCIENCE",
                        "subjectId": null,
                        "subjectCode": null,
                        "subjectName": null,
                        "designationId": null,
                        "designationCode": null,
                        "designationName": null,
                        "yearOfStudy": "*",
                        "typeOfProgramId": null,
                        "typeOfProgramCode": null,
                        "typeOfProgramName": null,
                        "primaryOrgId": null,
                        "primaryOrgCode": null,
                        "primaryOrgName": null,
                        "secondaryOrgId": null,
                        "secondaryOrgCode": null,
                        "secondaryOrgName": null,
                        "assocOrgId": null,
                        "assocOrgCode": null,
                        "assocOrgName": null,
                        "adminOrgId": null,
                        "adminOrgCode": null,
                        "adminOrgName": null
                    }
                ]
            },
            "LEC-0201": {
                "schedule": {
                    "MO-91009": {
                        "meetingDay": "MO",
                        "meetingStartTime": "16:00",
                        "meetingEndTime": "17:00",
                        "meetingScheduleId": "91009",
                        "assignedRoom1": "GB 244",
                        "assignedRoom2": null
                    },
                    "WE-91010": {
                        "meetingDay": "WE",
                        "meetingStartTime": "16:00",
                        "meetingEndTime": "17:00",
                        "meetingScheduleId": "91010",
                        "assignedRoom1": "GB 244",
                        "assignedRoom2": null
                    },
                    "FR-91011": {
                        "meetingDay": "FR",
                        "meetingStartTime": "16:00",
                        "meetingEndTime": "17:00",
                        "meetingScheduleId": "91011",
                        "assignedRoom1": "GB 244",
                        "assignedRoom2": null
                    }
                },
                "instructors": {
                    "2107221": {
                        "instructorId": "2107221",
                        "firstName": "J",
                        "lastName": "Gonzalez"
                    }
                },
                "meetingId": "16410",
                "teachingMethod": "LEC",
                "sectionNumber": "0201",
                "subtitle": "",
                "cancel": "",
                "waitlist": "Y",
                "online": "",
                "enrollmentCapacity": "100",
                "actualEnrolment": "94",
                "actualWaitlist": "0",
                "enrollmentIndicator": "P",
                "meetingStatusNotes": "",
                "enrollmentControls": [
                    {
                        "postId": "126",
                        "postCode": "ASMAJ1689",
                        "postName": "MA COMPUTER SCIENCE",
                        "subjectId": null,
                        "subjectCode": null,
                        "subjectName": null,
                        "designationId": null,
                        "designationCode": null,
                        "designationName": null,
                        "yearOfStudy": "*",
                        "typeOfProgramId": null,
                        "typeOfProgramCode": null,
                        "typeOfProgramName": null,
                        "primaryOrgId": null,
                        "primaryOrgCode": null,
                        "primaryOrgName": null,
                        "secondaryOrgId": null,
                        "secondaryOrgCode": null,
                        "secondaryOrgName": null,
                        "assocOrgId": null,
                        "assocOrgCode": null,
                        "assocOrgName": null,
                        "adminOrgId": null,
                        "adminOrgCode": null,
                        "adminOrgName": null
                    },
                    {
                        "postId": "127",
                        "postCode": "ASMAJ1689X",
                        "postName": "MA COMPUTER SCIENCE",
                        "subjectId": null,
                        "subjectCode": null,
                        "subjectName": null,
                        "designationId": null,
                        "designationCode": null,
                        "designationName": null,
                        "yearOfStudy": "*",
                        "typeOfProgramId": null,
                        "typeOfProgramCode": null,
                        "typeOfProgramName": null,
                        "primaryOrgId": null,
                        "primaryOrgCode": null,
                        "primaryOrgName": null,
                        "secondaryOrgId": null,
                        "secondaryOrgCode": null,
                        "secondaryOrgName": null,
                        "assocOrgId": null,
                        "assocOrgCode": null,
                        "assocOrgName": null,
                        "adminOrgId": null,
                        "adminOrgCode": null,
                        "adminOrgName": null
                    },
                    {
                        "postId": "212",
                        "postCode": "ASMIN1688",
                        "postName": "MI COMPUTER SCIENCE.",
                        "subjectId": null,
                        "subjectCode": null,
                        "subjectName": null,
                        "designationId": null,
                        "designationCode": null,
                        "designationName": null,
                        "yearOfStudy": "*",
                        "typeOfProgramId": null,
                        "typeOfProgramCode": null,
                        "typeOfProgramName": null,
                        "primaryOrgId": null,
                        "primaryOrgCode": null,
                        "primaryOrgName": null,
                        "secondaryOrgId": null,
                        "secondaryOrgCode": null,
                        "secondaryOrgName": null,
                        "assocOrgId": null,
                        "assocOrgCode": null,
                        "assocOrgName": null,
                        "adminOrgId": null,
                        "adminOrgCode": null,
                        "adminOrgName": null
                    },
                    {
                        "postId": "213",
                        "postCode": "ASMIN1689",
                        "postName": "MI COMPUTER SCIENCE",
                        "subjectId": null,
                        "subjectCode": null,
                        "subjectName": null,
                        "designationId": null,
                        "designationCode": null,
                        "designationName": null,
                        "yearOfStudy": "*",
                        "typeOfProgramId": null,
                        "typeOfProgramCode": null,
                        "typeOfProgramName": null,
                        "primaryOrgId": null,
                        "primaryOrgCode": null,
                        "primaryOrgName": null,
                        "secondaryOrgId": null,
                        "secondaryOrgCode": null,
                        "secondaryOrgName": null,
                        "assocOrgId": null,
                        "assocOrgCode": null,
                        "assocOrgName": null,
                        "adminOrgId": null,
                        "adminOrgCode": null,
                        "adminOrgName": null
                    },
                    {
                        "postId": "335",
                        "postCode": "ASSPE1689",
                        "postName": "SP COMPUTER SCIENCE",
                        "subjectId": null,
                        "subjectCode": null,
                        "subjectName": null,
                        "designationId": null,
                        "designationCode": null,
                        "designationName": null,
                        "yearOfStudy": "*",
                        "typeOfProgramId": null,
                        "typeOfProgramCode": null,
                        "typeOfProgramName": null,
                        "primaryOrgId": null,
                        "primaryOrgCode": null,
                        "primaryOrgName": null,
                        "secondaryOrgId": null,
                        "secondaryOrgCode": null,
                        "secondaryOrgName": null,
                        "assocOrgId": null,
                        "assocOrgCode": null,
                        "assocOrgName": null,
                        "adminOrgId": null,
                        "adminOrgCode": null,
                        "adminOrgName": null
                    },
                    {
                        "postId": "336",
                        "postCode": "ASSPE1689X",
                        "postName": "SP COMPUTER SCIENCE",
                        "subjectId": null,
                        "subjectCode": null,
                        "subjectName": null,
                        "designationId": null,
                        "designationCode": null,
                        "designationName": null,
                        "yearOfStudy": "*",
                        "typeOfProgramId": null,
                        "typeOfProgramCode": null,
                        "typeOfProgramName": null,
                        "primaryOrgId": null,
                        "primaryOrgCode": null,
                        "primaryOrgName": null,
                        "secondaryOrgId": null,
                        "secondaryOrgCode": null,
                        "secondaryOrgName": null,
                        "assocOrgId": null,
                        "assocOrgCode": null,
                        "assocOrgName": null,
                        "adminOrgId": null,
                        "adminOrgCode": null,
                        "adminOrgName": null
                    }
                ]
            },
            "LEC-2001": {
                "schedule": {
                    "MO-91884": {
                        "meetingDay": "MO",
                        "meetingStartTime": "15:00",
                        "meetingEndTime": "16:00",
                        "meetingScheduleId": "91884",
                        "assignedRoom1": "GB 244",
                        "assignedRoom2": null
                    },
                    "WE-91885": {
                        "meetingDay": "WE",
                        "meetingStartTime": "15:00",
                        "meetingEndTime": "16:00",
                        "meetingScheduleId": "91885",
                        "assignedRoom1": "GB 244",
                        "assignedRoom2": null
                    },
                    "FR-91886": {
                        "meetingDay": "FR",
                        "meetingStartTime": "15:00",
                        "meetingEndTime": "16:00",
                        "meetingScheduleId": "91886",
                        "assignedRoom1": "GB 244",
                        "assignedRoom2": null
                    }
                },
                "instructors": {
                    "2107222": {
                        "instructorId": "2107222",
                        "firstName": "J",
                        "lastName": "Gonzalez"
                    }
                },
                "meetingId": "26520",
                "teachingMethod": "LEC",
                "sectionNumber": "2001",
                "subtitle": "",
                "cancel": "",
                "waitlist": "Y",
                "online": "",
                "enrollmentCapacity": "15",
                "actualEnrolment": "15",
                "actualWaitlist": "0",
                "enrollmentIndicator": "R1",
                "meetingStatusNotes": "",
                "enrollmentControls": [
                    {
                        "postId": null,
                        "postCode": null,
                        "postName": null,
                        "subjectId": "1",
                        "subjectCode": "*",
                        "subjectName": "",
                        "designationId": "1",
                        "designationCode": "*",
                        "designationName": "",
                        "yearOfStudy": "*",
                        "typeOfProgramId": null,
                        "typeOfProgramCode": null,
                        "typeOfProgramName": null,
                        "primaryOrgId": "4",
                        "primaryOrgCode": "APSC",
                        "primaryOrgName": "Faculty of Applied Science & Engineering",
                        "secondaryOrgId": "1",
                        "secondaryOrgCode": "*",
                        "secondaryOrgName": "",
                        "assocOrgId": "1",
                        "assocOrgCode": "*",
                        "assocOrgName": "",
                        "adminOrgId": "1",
                        "adminOrgCode": "*",
                        "adminOrgName": ""
                    }
                ]
            }
        }
    }